units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2

points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        outer:
          key:
            splay:
        pinky:
          key:
            splay: -3 
            stagger: 1
            origin: [0, -10]
        ring:
          key:
            splay: -4
            origin: [0, -10]
            stagger: 12
        middle:
          key:
            stagger: 3
        index:
          key:
            stagger: -3
        inner:
          key:
            stagger: -3
          rows.mod.skip: true
      rows:
        mod:
        bottom:
        home:
        top:
        
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_mod
        shift: [-34, -25]
      columns:
        layer:
          key:
            splay: 20
        space:
          key:
            width: 1kx
            splay: 10
            shift: [2,-2]
        key:
          key:
            width: 1kx
            splay: -35
            shift: [3, 9]
      rows:
        cluster:

  rotate: -20
  
  mirror: &mirror
    ref: matrix_pinky_home
    distance: 12kx

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  left_board_keys_outline:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
    - what: polygon
      bound: false
      operation: stack

      points:
        - ref: matrix_outer_mod
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_mod
          shift: [-0.5px,-0.6py]
        - ref: matrix_ring_mod
          shift: [0px,-1.2py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.0px,-0.6py]
        - ref: thumbs_key_cluster
          shift: [0.5px,-0.5py]

        - ref: matrix_inner_bottom
          shift: [0.7px,0py]
        - ref: matrix_inner_home
          shift: [0.6px,0.0py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_index_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0px,0.6py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_top
          shift: [0.6px,0.6py]
        - ref: matrix_outer_top
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,0.5py]

  right_board_keys_outline:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_mod
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_mod
          shift: [-0.5px,-0.6py]
        - ref: mirror_matrix_ring_mod
          shift: [0px,-1.2py]
        - ref: mirror_thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_space_cluster
          shift: [-0.0px,-0.6py]
        - ref: mirror_thumbs_key_cluster
          shift: [0.5px,-0.5py]

        - ref: mirror_matrix_inner_bottom
          shift: [0.7px,0py]
        - ref: mirror_matrix_inner_home
          shift: [0.6px,0.0py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0px,0.6py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [0.6px,0.6py]
        - ref: mirror_matrix_outer_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_outer_home
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px,0.5py]

  left_board_outline:
    - what: polygon
      bound: false
      operation: stack
      points:
        - ref: matrix_outer_mod
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_mod
          shift: [-0.5px,-0.6py]
        - ref: matrix_ring_mod
          shift: [0px,-1.2py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: thumbs_space_cluster
          shift: [-0.0px,-0.6py]
        - ref: thumbs_key_cluster
          shift: [0.5px,-0.5py]

        - ref: matrix_inner_bottom
          shift: [0.7px,0py]
        - ref: matrix_inner_home
          shift: [0.6px,0.0py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: matrix_index_top
          shift: [0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0px,0.6py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_pinky_top
          shift: [0.6px,0.6py]
        - ref: matrix_outer_top
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px,0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,0.5py]

  right_board_outline:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_mod
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_mod
          shift: [-0.5px,-0.6py]
        - ref: mirror_matrix_ring_mod
          shift: [0px,-1.2py]
        - ref: mirror_thumbs_layer_cluster
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_space_cluster
          shift: [-0.0px,-0.6py]
        - ref: mirror_thumbs_key_cluster
          shift: [0.5px,-0.5py]

        - ref: mirror_matrix_inner_bottom
          shift: [0.7px,0py]
        - ref: mirror_matrix_inner_home
          shift: [0.6px,0.0py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0px,0.6py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [0.6px,0.6py]
        - ref: mirror_matrix_outer_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_outer_home
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px,0.5py]